mapping:
    NAD:
      2:
        1: "adress_type"
      3:
        1: "location_number"
        3: "location_number_org"
      5:
        1: "name_line_1"
        2: "name_line_2"
      6:
        1: "address"
      7:
        1: "city"
      9:
        1: "zip"
      10:
        1: "country"
    BGM:
      2:
        1: "document_name_code"
      3: 
        1: "document_identification"
      4:
        1: "message_function"
    ALI:
      4: 
        1: "code_scenario"
    FTX:
      2:
        1: "information_type"
      4:
        1: "print_location"
      5:
        1: "information_content"  
    LIN:
      2:
        1: "line_number"
      4:
        1: "product_identification" 
        2: "identification_type"
    PIA:
      2:
        1: "identification_type"
      3:  
        1: "identification"
        2: "identification_org"
    QTY:
      2: 
        1: "quantity_type"
        2: "quantity"
        3: "measurement_unit"
    IMD:
      2: 
        1: "description_format"
      3:
        1: "description_type"
      4:
        4: "description"
        
structure:
    UNH: { min: 1, max: 1}
    BGM: { min: 1, max: 1}
    DTM: { min: 1, max: 4}
    RFF: { min: 0, max: 1}
    ALI: { min: 0, max: 2}
    FTX: { min: 0, max: 99}
    NAD: { min: 2, max: 5}
    LIN:
      min: 1
      max: 200000
      isGroup: true
      groupName: order_lines
      children:
        LIN: {min: 1, max: 1}
        IMD: {min: 0, max: 99}
        PIA: {min: 0, max: 1}
        QTY: {min: 1, max: 1}
    UNS: {min: 1, max: 1}
    UNT: {min: 1, max: 1}